include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_dynamic_calls: error
    invalid_annotation_target: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_print: true
    avoid_dynamic_calls: true
    always_use_package_imports: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    sort_constructors_first: true
    use_super_parameters: true
